# Github workflow to compile latex and deploy the pdf to an orphan branch.
# Davide Gerosa (2021) https://github.com/dgerosa

# Edit the DIR and FILE variables with the location of the latex file.
# Place the yml file in a directory called .github/workflows

# The latest compiled pdf is made available at e.g.
# https://github.com/dgerosa/[repositoryname]/blob/build/[filename].pdf

# You can also add a badge to your README:
# [![compile_deploy_latex](https://github.com/dgerosa/[repositoryname]/actions/workflows/compile_deploy_latex.yml/badge.svg)](https://github.com/dgerosa/[repositoryname]/actions)

# To compile multiple papers, duplicate the job called "paper" with different FILE/DIR names and add the "needs" line in the "deploy" job accordingly  

name: work with file
on: [push]
jobs:
  Server1:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: draft
      FILE: file1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: complite
        run: echo "abc" >> file1 
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.FILE }} ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE }}
          path: ./github_artifacts
  Server2:
    # Edit here if compiling multiple papers
    needs: [Server1]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/*   github_deploy &&  cat github_deploy/file1 >> github_deploy/file2 && echo "2" >> github_deploy/file2
      - name: move file2
        run: mv github_deploy/file2 ./github_artifacts/
      - name: move file2 to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: file2
          path: ./github_artifacts                                                                                                                  
  Server3:
   needs: [Server1]
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/*   github_deploy &&  cat github_deploy/file1 >> github_deploy/file3 && echo "3" >> github_deploy/file3
      - name: move file3
        run: mv github_deploy/file3 ./github_artifacts/
      - name: move file3 to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: file3
          path: ./github_artifacts                          
  Server4:
   needs: [Server2]
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/*   github_deploy &&  cat github_deploy/file2 >> github_deploy/file4 && echo "4" >> github_deploy/file4
      - name: move file4
        run: mv github_deploy/file4 ./github_artifacts/
      - name: move file4 to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: file4
          path: ./github_artifacts  
  Server5:
   needs: [Server3]
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/*   github_deploy &&  cat github_deploy/file3 >> github_deploy/file5 && echo "5" >> github_deploy/file5
      - name: move file5
        run: mv github_deploy/file5 ./github_artifacts/
      - name: move file5 to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: file5
          path: ./github_artifacts 
  Server6:
    needs: [Server4, 5]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/*   github_deploy &&  cat github_deploy/file4 >> github_deploy/file6 && github_deploy/file5 >> github_deploy/file6 
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
  
    

